### ISSUE TITLE
United Nations

### ISSUE THREAD

**Issue by AndreasBrostrom** [AndreasBrostrom/ExtendedTimeline#9]
**United Nations** (UN)

### TODO
- [ ] UN Formation (26 June 1945) > Trigger 4 months after WW2
  UN is not a faction
  All nations are considered UN members
  Non-UN members have a idea
  - [ ] UN event formation
  - [ ] UN USA focus tree formation
- UN Decisions
  - Interventions
  - Resolutions
- [ ] UN Security Council
  Have a national idea
